import { STRING_LITERAL_DROP_BUNDLE } from "next/dist/shared/lib/constants";
import Head from "next/head";
import Image from "next/image";
import  CardCarousel from "../components/CardCarousel";

export default function Home() {
  return (
    <>
      <Head>
        <title>The Boat Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="Home">
        <h1>Home</h1>
        <div>
        {/* actualités en carousel defilant de 6 secondes */}
          <h2>Actualités du projet</h2>
          <CardCarousel /> 
        </div>
      </div>
    </>
  );
}
